name: fitdata_warehouse
version: "1.0.0"
config-version: 2
profile: fitdata

model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  fitdata_warehouse:
    staging:
      +schema: staging
      +materialized: view
    analytics:
      +schema: analytics
      +materialized: table
